<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-OET6KL6" failures="0" tests="18" name="Tests.LoginTest" time="20.251" errors="1" timestamp="2024-06-13T16:05:48 IST" skipped="17">
  <testcase classname="Tests.LoginTest" name="StartApp" time="20.251">
    <error message="The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m&#039;127.0.0.1&#039;[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

" type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
      <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
    </error>
  </testcase> <!-- StartApp -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_001_Verify_Login_With_Valid_Credentials" time="0.000">
    <skipped/>
  </testcase> <!-- TC_001_Verify_Login_With_Valid_Credentials -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_002_Verify_Login_With_Invalid_Username" time="0.000">
    <skipped/>
  </testcase> <!-- TC_002_Verify_Login_With_Invalid_Username -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_003_Verify_Login_With_Invalid_Password" time="0.000">
    <skipped/>
  </testcase> <!-- TC_003_Verify_Login_With_Invalid_Password -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_004_Verify_Login_With_Invalid_Project" time="0.000">
    <skipped/>
  </testcase> <!-- TC_004_Verify_Login_With_Invalid_Project -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_005_Verify_Login_With_Invalid_Mobile_Number" time="0.000">
    <skipped/>
  </testcase> <!-- TC_005_Verify_Login_With_Invalid_Mobile_Number -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_006_Verify_Login_Without_Entering_Username" time="0.000">
    <skipped/>
  </testcase> <!-- TC_006_Verify_Login_Without_Entering_Username -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_007_Verify_Login_Without_Entering_Password" time="0.000">
    <skipped/>
  </testcase> <!-- TC_007_Verify_Login_Without_Entering_Password -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_008_Verify_Login_Without_Entering_Project" time="0.000">
    <skipped/>
  </testcase> <!-- TC_008_Verify_Login_Without_Entering_Project -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_009_Verify_Login_Without_Entering_Mobile_Number" time="0.000">
    <skipped/>
  </testcase> <!-- TC_009_Verify_Login_Without_Entering_Mobile_Number -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_010_Verify_UsernameTextboxCharacterLimit" time="0.000">
    <skipped/>
  </testcase> <!-- TC_010_Verify_UsernameTextboxCharacterLimit -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_011_Verify_UsernameTextboxAcceptsSpecialCharacters" time="0.000">
    <skipped/>
  </testcase> <!-- TC_011_Verify_UsernameTextboxAcceptsSpecialCharacters -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_012_Verify_UsernameTextboxAcceptsNumbers" time="0.000">
    <skipped/>
  </testcase> <!-- TC_012_Verify_UsernameTextboxAcceptsNumbers -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_013_Verify_PasswordTextboxCharacterLimit" time="0.000">
    <skipped/>
  </testcase> <!-- TC_013_Verify_PasswordTextboxCharacterLimit -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_014_Verify_ProjectTextboxCharacterLimit" time="0.000">
    <skipped/>
  </testcase> <!-- TC_014_Verify_ProjectTextboxCharacterLimit -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_015_Verify_ProjectTextboxAcceptsSpecialCharacters" time="0.000">
    <skipped/>
  </testcase> <!-- TC_015_Verify_ProjectTextboxAcceptsSpecialCharacters -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_016_Verify_ProjectTextboxAcceptsNumbers" time="0.000">
    <skipped/>
  </testcase> <!-- TC_016_Verify_ProjectTextboxAcceptsNumbers -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_017_Verify_MobileNumberTextboxCharacterLimit" time="0.000">
    <skipped/>
  </testcase> <!-- TC_017_Verify_MobileNumberTextboxCharacterLimit -->
  <system-out/>
</testsuite> <!-- Tests.LoginTest -->
