<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-OET6KL6" failures="3" tests="17" name="Tests.LoginTest" time="157.352" errors="0" timestamp="2024-05-27T17:55:20 IST" skipped="0">
  <testcase classname="Tests.LoginTest" name="TC_001_Verify_Login_With_Valid_Credentials" time="20.588"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_002_Verify_Login_With_Invalid_Username" time="13.189"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_003_Verify_Login_With_Invalid_Password" time="14.659"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_004_Verify_Login_With_Invalid_Project" time="16.996"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_005_Verify_Login_With_Invalid_Mobile_Number" time="14.359"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_006_Verify_Login_Without_Entering_Username" time="13.921"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_007_Verify_Login_Without_Entering_Password" time="12.080"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_008_Verify_Login_Without_Entering_Project" time="12.955"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_009_Verify_Login_Without_Entering_Mobile_Number" time="11.527"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_010_Verify_UsernameTextboxCharacterLimit" time="3.073">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Modules.Login_Module.validateMaxTextLimit(Login_Module.java:68)
at Modules.Login_Module.validateMaxTextLimitInUsernameTextbox(Login_Module.java:102)
at Tests.LoginTest.TC_010_Verify_UsernameTextboxCharacterLimit(LoginTest.java:133)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at Tests.Main.main(Main.java:34)
]]>
    </failure>
  </testcase> <!-- TC_010_Verify_UsernameTextboxCharacterLimit -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_011_Verify_UsernameTextboxAcceptsSpecialCharacters" time="3.031"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_012_Verify_UsernameTextboxAcceptsNumbers" time="2.764"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_013_Verify_PasswordTextboxCharacterLimit" time="2.796">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Modules.Login_Module.validateMaxTextLimit(Login_Module.java:68)
at Modules.Login_Module.validateMaxTextLimitInPasswordTextbox(Login_Module.java:114)
at Tests.LoginTest.TC_013_Verify_PasswordTextboxCharacterLimit(LoginTest.java:150)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at Tests.Main.main(Main.java:34)
]]>
    </failure>
  </testcase> <!-- TC_013_Verify_PasswordTextboxCharacterLimit -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_014_Verify_ProjectTextboxCharacterLimit" time="3.877">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Modules.Login_Module.validateMaxTextLimit(Login_Module.java:68)
at Modules.Login_Module.validateMaxTextLimitInProjectTextbox(Login_Module.java:118)
at Tests.LoginTest.TC_014_Verify_ProjectTextboxCharacterLimit(LoginTest.java:156)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at Tests.Main.main(Main.java:34)
]]>
    </failure>
  </testcase> <!-- TC_014_Verify_ProjectTextboxCharacterLimit -->
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_015_Verify_ProjectTextboxAcceptsSpecialCharacters" time="3.217"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_016_Verify_ProjectTextboxAcceptsNumbers" time="2.989"/>
  <system-out/>
  <testcase classname="Tests.LoginTest" name="TC_017_Verify_MobileNumberTextboxCharacterLimit" time="5.331"/>
  <system-out/>
</testsuite> <!-- Tests.LoginTest -->
